name: CI - Build to Nuget

on:
  create:
    branches: 
      - release/**
  push:
    branches:
      - master
      - release/**

  pull_request:
    branches:
      - master
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'PokemonTcgSdk.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

    - name: Run tests
      run: dotnet test -c Release --no-build --verbosity normal --filter "Category!=LongRunning"
      
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: dotnet nuget push **/*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
